//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberSharkPlugin.CallLogsService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenericResult", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx")]
    [System.SerializableAttribute()]
    public partial class GenericResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool ResultField;
        
        private int ResultCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ResultCode {
            get {
                return this.ResultCodeField;
            }
            set {
                if ((this.ResultCodeField.Equals(value) != true)) {
                    this.ResultCodeField = value;
                    this.RaisePropertyChanged("ResultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallLogIdResult", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx")]
    [System.SerializableAttribute()]
    public partial class CallLogIdResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool ResultField;
        
        private int ResultCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        private int CallLogIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CallNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ResultCode {
            get {
                return this.ResultCodeField;
            }
            set {
                if ((this.ResultCodeField.Equals(value) != true)) {
                    this.ResultCodeField = value;
                    this.RaisePropertyChanged("ResultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int CallLogId {
            get {
                return this.CallLogIdField;
            }
            set {
                if ((this.CallLogIdField.Equals(value) != true)) {
                    this.CallLogIdField = value;
                    this.RaisePropertyChanged("CallLogId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CallNumber {
            get {
                return this.CallNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CallNumberField, value) != true)) {
                    this.CallNumberField = value;
                    this.RaisePropertyChanged("CallNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallLogInfoResult", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx")]
    [System.SerializableAttribute()]
    public partial class CallLogInfoResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool ResultField;
        
        private int ResultCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        private CyberSharkPlugin.CallLogsService.CallLogInfo CallLogField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ResultCode {
            get {
                return this.ResultCodeField;
            }
            set {
                if ((this.ResultCodeField.Equals(value) != true)) {
                    this.ResultCodeField = value;
                    this.RaisePropertyChanged("ResultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public CyberSharkPlugin.CallLogsService.CallLogInfo CallLog {
            get {
                return this.CallLogField;
            }
            set {
                if ((object.ReferenceEquals(this.CallLogField, value) != true)) {
                    this.CallLogField = value;
                    this.RaisePropertyChanged("CallLog");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallLogInfo", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx")]
    [System.SerializableAttribute()]
    public partial class CallLogInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        private System.DateTime StartTimeField;
        
        private System.DateTime EndTimeField;
        
        private System.DateTime DateCreatedField;
        
        private System.Nullable<System.DateTime> DateDeletedField;
        
        private int GroupIDField;
        
        private int AgentIDField;
        
        private int LogIDField;
        
        private bool IncomingCallField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CallNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((this.EndTimeField.Equals(value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime DateCreated {
            get {
                return this.DateCreatedField;
            }
            set {
                if ((this.DateCreatedField.Equals(value) != true)) {
                    this.DateCreatedField = value;
                    this.RaisePropertyChanged("DateCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.Nullable<System.DateTime> DateDeleted {
            get {
                return this.DateDeletedField;
            }
            set {
                if ((this.DateDeletedField.Equals(value) != true)) {
                    this.DateDeletedField = value;
                    this.RaisePropertyChanged("DateDeleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int GroupID {
            get {
                return this.GroupIDField;
            }
            set {
                if ((this.GroupIDField.Equals(value) != true)) {
                    this.GroupIDField = value;
                    this.RaisePropertyChanged("GroupID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int AgentID {
            get {
                return this.AgentIDField;
            }
            set {
                if ((this.AgentIDField.Equals(value) != true)) {
                    this.AgentIDField = value;
                    this.RaisePropertyChanged("AgentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public int LogID {
            get {
                return this.LogIDField;
            }
            set {
                if ((this.LogIDField.Equals(value) != true)) {
                    this.LogIDField = value;
                    this.RaisePropertyChanged("LogID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public bool IncomingCall {
            get {
                return this.IncomingCallField;
            }
            set {
                if ((this.IncomingCallField.Equals(value) != true)) {
                    this.IncomingCallField = value;
                    this.RaisePropertyChanged("IncomingCall");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string CallNumber {
            get {
                return this.CallNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CallNumberField, value) != true)) {
                    this.CallNumberField = value;
                    this.RaisePropertyChanged("CallNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallLogInfoResultArray", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx")]
    [System.SerializableAttribute()]
    public partial class CallLogInfoResultArray : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool ResultField;
        
        private int ResultCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CyberSharkPlugin.CallLogsService.CallLogInfo[] CallLogsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ResultCode {
            get {
                return this.ResultCodeField;
            }
            set {
                if ((this.ResultCodeField.Equals(value) != true)) {
                    this.ResultCodeField = value;
                    this.RaisePropertyChanged("ResultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public CyberSharkPlugin.CallLogsService.CallLogInfo[] CallLogs {
            get {
                return this.CallLogsField;
            }
            set {
                if ((object.ReferenceEquals(this.CallLogsField, value) != true)) {
                    this.CallLogsField = value;
                    this.RaisePropertyChanged("CallLogs");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx", ConfigurationName="CallLogsService.svcCallLogsSoap")]
    public interface svcCallLogsSoap {
        
        // CODEGEN: Generating message contract since element name authUserName from namespace http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx/CreateCallLog" +
            "", ReplyAction="*")]
        CyberSharkPlugin.CallLogsService.CreateCallLogResponse CreateCallLog(CyberSharkPlugin.CallLogsService.CreateCallLogRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx/CreateCallLog" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task<CyberSharkPlugin.CallLogsService.CreateCallLogResponse> CreateCallLogAsync(CyberSharkPlugin.CallLogsService.CreateCallLogRequest request);
        
        // CODEGEN: Generating message contract since element name authUserName from namespace http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx/CreateCallLog" +
            "2", ReplyAction="*")]
        CyberSharkPlugin.CallLogsService.CreateCallLog2Response CreateCallLog2(CyberSharkPlugin.CallLogsService.CreateCallLog2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx/CreateCallLog" +
            "2", ReplyAction="*")]
        System.Threading.Tasks.Task<CyberSharkPlugin.CallLogsService.CreateCallLog2Response> CreateCallLog2Async(CyberSharkPlugin.CallLogsService.CreateCallLog2Request request);
        
        // CODEGEN: Generating message contract since element name authUserName from namespace http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx/ModifyCallLog" +
            "", ReplyAction="*")]
        CyberSharkPlugin.CallLogsService.ModifyCallLogResponse ModifyCallLog(CyberSharkPlugin.CallLogsService.ModifyCallLogRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx/ModifyCallLog" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task<CyberSharkPlugin.CallLogsService.ModifyCallLogResponse> ModifyCallLogAsync(CyberSharkPlugin.CallLogsService.ModifyCallLogRequest request);
        
        // CODEGEN: Generating message contract since element name authUserName from namespace http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx/DeleteCallLog" +
            "", ReplyAction="*")]
        CyberSharkPlugin.CallLogsService.DeleteCallLogResponse DeleteCallLog(CyberSharkPlugin.CallLogsService.DeleteCallLogRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx/DeleteCallLog" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task<CyberSharkPlugin.CallLogsService.DeleteCallLogResponse> DeleteCallLogAsync(CyberSharkPlugin.CallLogsService.DeleteCallLogRequest request);
        
        // CODEGEN: Generating message contract since element name authUserName from namespace http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx/GetCallLog", ReplyAction="*")]
        CyberSharkPlugin.CallLogsService.GetCallLogResponse GetCallLog(CyberSharkPlugin.CallLogsService.GetCallLogRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx/GetCallLog", ReplyAction="*")]
        System.Threading.Tasks.Task<CyberSharkPlugin.CallLogsService.GetCallLogResponse> GetCallLogAsync(CyberSharkPlugin.CallLogsService.GetCallLogRequest request);
        
        // CODEGEN: Generating message contract since element name authUserName from namespace http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx/GetCallLogByU" +
            "ser", ReplyAction="*")]
        CyberSharkPlugin.CallLogsService.GetCallLogByUserResponse GetCallLogByUser(CyberSharkPlugin.CallLogsService.GetCallLogByUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx/GetCallLogByU" +
            "ser", ReplyAction="*")]
        System.Threading.Tasks.Task<CyberSharkPlugin.CallLogsService.GetCallLogByUserResponse> GetCallLogByUserAsync(CyberSharkPlugin.CallLogsService.GetCallLogByUserRequest request);
        
        // CODEGEN: Generating message contract since element name authUserName from namespace http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx/GetCallLogByG" +
            "roup", ReplyAction="*")]
        CyberSharkPlugin.CallLogsService.GetCallLogByGroupResponse GetCallLogByGroup(CyberSharkPlugin.CallLogsService.GetCallLogByGroupRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx/GetCallLogByG" +
            "roup", ReplyAction="*")]
        System.Threading.Tasks.Task<CyberSharkPlugin.CallLogsService.GetCallLogByGroupResponse> GetCallLogByGroupAsync(CyberSharkPlugin.CallLogsService.GetCallLogByGroupRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateCallLogRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateCallLog", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx", Order=0)]
        public CyberSharkPlugin.CallLogsService.CreateCallLogRequestBody Body;
        
        public CreateCallLogRequest() {
        }
        
        public CreateCallLogRequest(CyberSharkPlugin.CallLogsService.CreateCallLogRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx")]
    public partial class CreateCallLogRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string authUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string authPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public CyberSharkPlugin.CallLogsService.ArrayOfString parameters;
        
        public CreateCallLogRequestBody() {
        }
        
        public CreateCallLogRequestBody(string authUserName, string authPassword, CyberSharkPlugin.CallLogsService.ArrayOfString parameters) {
            this.authUserName = authUserName;
            this.authPassword = authPassword;
            this.parameters = parameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateCallLogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateCallLogResponse", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx", Order=0)]
        public CyberSharkPlugin.CallLogsService.CreateCallLogResponseBody Body;
        
        public CreateCallLogResponse() {
        }
        
        public CreateCallLogResponse(CyberSharkPlugin.CallLogsService.CreateCallLogResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx")]
    public partial class CreateCallLogResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CyberSharkPlugin.CallLogsService.GenericResult CreateCallLogResult;
        
        public CreateCallLogResponseBody() {
        }
        
        public CreateCallLogResponseBody(CyberSharkPlugin.CallLogsService.GenericResult CreateCallLogResult) {
            this.CreateCallLogResult = CreateCallLogResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateCallLog2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateCallLog2", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx", Order=0)]
        public CyberSharkPlugin.CallLogsService.CreateCallLog2RequestBody Body;
        
        public CreateCallLog2Request() {
        }
        
        public CreateCallLog2Request(CyberSharkPlugin.CallLogsService.CreateCallLog2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx")]
    public partial class CreateCallLog2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string authUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string authPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public CyberSharkPlugin.CallLogsService.ArrayOfString parameters;
        
        public CreateCallLog2RequestBody() {
        }
        
        public CreateCallLog2RequestBody(string authUserName, string authPassword, CyberSharkPlugin.CallLogsService.ArrayOfString parameters) {
            this.authUserName = authUserName;
            this.authPassword = authPassword;
            this.parameters = parameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateCallLog2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateCallLog2Response", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx", Order=0)]
        public CyberSharkPlugin.CallLogsService.CreateCallLog2ResponseBody Body;
        
        public CreateCallLog2Response() {
        }
        
        public CreateCallLog2Response(CyberSharkPlugin.CallLogsService.CreateCallLog2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx")]
    public partial class CreateCallLog2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CyberSharkPlugin.CallLogsService.CallLogIdResult CreateCallLog2Result;
        
        public CreateCallLog2ResponseBody() {
        }
        
        public CreateCallLog2ResponseBody(CyberSharkPlugin.CallLogsService.CallLogIdResult CreateCallLog2Result) {
            this.CreateCallLog2Result = CreateCallLog2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModifyCallLogRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModifyCallLog", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx", Order=0)]
        public CyberSharkPlugin.CallLogsService.ModifyCallLogRequestBody Body;
        
        public ModifyCallLogRequest() {
        }
        
        public ModifyCallLogRequest(CyberSharkPlugin.CallLogsService.ModifyCallLogRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx")]
    public partial class ModifyCallLogRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string authUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string authPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int logID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public CyberSharkPlugin.CallLogsService.ArrayOfString parameters;
        
        public ModifyCallLogRequestBody() {
        }
        
        public ModifyCallLogRequestBody(string authUserName, string authPassword, int logID, CyberSharkPlugin.CallLogsService.ArrayOfString parameters) {
            this.authUserName = authUserName;
            this.authPassword = authPassword;
            this.logID = logID;
            this.parameters = parameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModifyCallLogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModifyCallLogResponse", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx", Order=0)]
        public CyberSharkPlugin.CallLogsService.ModifyCallLogResponseBody Body;
        
        public ModifyCallLogResponse() {
        }
        
        public ModifyCallLogResponse(CyberSharkPlugin.CallLogsService.ModifyCallLogResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx")]
    public partial class ModifyCallLogResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CyberSharkPlugin.CallLogsService.GenericResult ModifyCallLogResult;
        
        public ModifyCallLogResponseBody() {
        }
        
        public ModifyCallLogResponseBody(CyberSharkPlugin.CallLogsService.GenericResult ModifyCallLogResult) {
            this.ModifyCallLogResult = ModifyCallLogResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteCallLogRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteCallLog", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx", Order=0)]
        public CyberSharkPlugin.CallLogsService.DeleteCallLogRequestBody Body;
        
        public DeleteCallLogRequest() {
        }
        
        public DeleteCallLogRequest(CyberSharkPlugin.CallLogsService.DeleteCallLogRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx")]
    public partial class DeleteCallLogRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string authUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string authPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int logID;
        
        public DeleteCallLogRequestBody() {
        }
        
        public DeleteCallLogRequestBody(string authUserName, string authPassword, int logID) {
            this.authUserName = authUserName;
            this.authPassword = authPassword;
            this.logID = logID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteCallLogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteCallLogResponse", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx", Order=0)]
        public CyberSharkPlugin.CallLogsService.DeleteCallLogResponseBody Body;
        
        public DeleteCallLogResponse() {
        }
        
        public DeleteCallLogResponse(CyberSharkPlugin.CallLogsService.DeleteCallLogResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx")]
    public partial class DeleteCallLogResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CyberSharkPlugin.CallLogsService.GenericResult DeleteCallLogResult;
        
        public DeleteCallLogResponseBody() {
        }
        
        public DeleteCallLogResponseBody(CyberSharkPlugin.CallLogsService.GenericResult DeleteCallLogResult) {
            this.DeleteCallLogResult = DeleteCallLogResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCallLogRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCallLog", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx", Order=0)]
        public CyberSharkPlugin.CallLogsService.GetCallLogRequestBody Body;
        
        public GetCallLogRequest() {
        }
        
        public GetCallLogRequest(CyberSharkPlugin.CallLogsService.GetCallLogRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx")]
    public partial class GetCallLogRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string authUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string authPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int logID;
        
        public GetCallLogRequestBody() {
        }
        
        public GetCallLogRequestBody(string authUserName, string authPassword, int logID) {
            this.authUserName = authUserName;
            this.authPassword = authPassword;
            this.logID = logID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCallLogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCallLogResponse", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx", Order=0)]
        public CyberSharkPlugin.CallLogsService.GetCallLogResponseBody Body;
        
        public GetCallLogResponse() {
        }
        
        public GetCallLogResponse(CyberSharkPlugin.CallLogsService.GetCallLogResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx")]
    public partial class GetCallLogResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CyberSharkPlugin.CallLogsService.CallLogInfoResult GetCallLogResult;
        
        public GetCallLogResponseBody() {
        }
        
        public GetCallLogResponseBody(CyberSharkPlugin.CallLogsService.CallLogInfoResult GetCallLogResult) {
            this.GetCallLogResult = GetCallLogResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCallLogByUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCallLogByUser", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx", Order=0)]
        public CyberSharkPlugin.CallLogsService.GetCallLogByUserRequestBody Body;
        
        public GetCallLogByUserRequest() {
        }
        
        public GetCallLogByUserRequest(CyberSharkPlugin.CallLogsService.GetCallLogByUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx")]
    public partial class GetCallLogByUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string authUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string authPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int userID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime dateCreatedStart;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime dateCreatedEnd;
        
        public GetCallLogByUserRequestBody() {
        }
        
        public GetCallLogByUserRequestBody(string authUserName, string authPassword, int userID, System.DateTime dateCreatedStart, System.DateTime dateCreatedEnd) {
            this.authUserName = authUserName;
            this.authPassword = authPassword;
            this.userID = userID;
            this.dateCreatedStart = dateCreatedStart;
            this.dateCreatedEnd = dateCreatedEnd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCallLogByUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCallLogByUserResponse", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx", Order=0)]
        public CyberSharkPlugin.CallLogsService.GetCallLogByUserResponseBody Body;
        
        public GetCallLogByUserResponse() {
        }
        
        public GetCallLogByUserResponse(CyberSharkPlugin.CallLogsService.GetCallLogByUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx")]
    public partial class GetCallLogByUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CyberSharkPlugin.CallLogsService.CallLogInfoResultArray GetCallLogByUserResult;
        
        public GetCallLogByUserResponseBody() {
        }
        
        public GetCallLogByUserResponseBody(CyberSharkPlugin.CallLogsService.CallLogInfoResultArray GetCallLogByUserResult) {
            this.GetCallLogByUserResult = GetCallLogByUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCallLogByGroupRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCallLogByGroup", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx", Order=0)]
        public CyberSharkPlugin.CallLogsService.GetCallLogByGroupRequestBody Body;
        
        public GetCallLogByGroupRequest() {
        }
        
        public GetCallLogByGroupRequest(CyberSharkPlugin.CallLogsService.GetCallLogByGroupRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx")]
    public partial class GetCallLogByGroupRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string authUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string authPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int groupID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime dateCreatedStart;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime dateCreatedEnd;
        
        public GetCallLogByGroupRequestBody() {
        }
        
        public GetCallLogByGroupRequestBody(string authUserName, string authPassword, int groupID, System.DateTime dateCreatedStart, System.DateTime dateCreatedEnd) {
            this.authUserName = authUserName;
            this.authPassword = authPassword;
            this.groupID = groupID;
            this.dateCreatedStart = dateCreatedStart;
            this.dateCreatedEnd = dateCreatedEnd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCallLogByGroupResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCallLogByGroupResponse", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx", Order=0)]
        public CyberSharkPlugin.CallLogsService.GetCallLogByGroupResponseBody Body;
        
        public GetCallLogByGroupResponse() {
        }
        
        public GetCallLogByGroupResponse(CyberSharkPlugin.CallLogsService.GetCallLogByGroupResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx")]
    public partial class GetCallLogByGroupResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CyberSharkPlugin.CallLogsService.CallLogInfoResultArray GetCallLogByGroupResult;
        
        public GetCallLogByGroupResponseBody() {
        }
        
        public GetCallLogByGroupResponseBody(CyberSharkPlugin.CallLogsService.CallLogInfoResultArray GetCallLogByGroupResult) {
            this.GetCallLogByGroupResult = GetCallLogByGroupResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface svcCallLogsSoapChannel : CyberSharkPlugin.CallLogsService.svcCallLogsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class svcCallLogsSoapClient : System.ServiceModel.ClientBase<CyberSharkPlugin.CallLogsService.svcCallLogsSoap>, CyberSharkPlugin.CallLogsService.svcCallLogsSoap {
        
        public svcCallLogsSoapClient() {
        }
        
        public svcCallLogsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public svcCallLogsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public svcCallLogsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public svcCallLogsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CyberSharkPlugin.CallLogsService.CreateCallLogResponse CyberSharkPlugin.CallLogsService.svcCallLogsSoap.CreateCallLog(CyberSharkPlugin.CallLogsService.CreateCallLogRequest request) {
            return base.Channel.CreateCallLog(request);
        }
        
        public CyberSharkPlugin.CallLogsService.GenericResult CreateCallLog(string authUserName, string authPassword, CyberSharkPlugin.CallLogsService.ArrayOfString parameters) {
            CyberSharkPlugin.CallLogsService.CreateCallLogRequest inValue = new CyberSharkPlugin.CallLogsService.CreateCallLogRequest();
            inValue.Body = new CyberSharkPlugin.CallLogsService.CreateCallLogRequestBody();
            inValue.Body.authUserName = authUserName;
            inValue.Body.authPassword = authPassword;
            inValue.Body.parameters = parameters;
            CyberSharkPlugin.CallLogsService.CreateCallLogResponse retVal = ((CyberSharkPlugin.CallLogsService.svcCallLogsSoap)(this)).CreateCallLog(inValue);
            return retVal.Body.CreateCallLogResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CyberSharkPlugin.CallLogsService.CreateCallLogResponse> CyberSharkPlugin.CallLogsService.svcCallLogsSoap.CreateCallLogAsync(CyberSharkPlugin.CallLogsService.CreateCallLogRequest request) {
            return base.Channel.CreateCallLogAsync(request);
        }
        
        public System.Threading.Tasks.Task<CyberSharkPlugin.CallLogsService.CreateCallLogResponse> CreateCallLogAsync(string authUserName, string authPassword, CyberSharkPlugin.CallLogsService.ArrayOfString parameters) {
            CyberSharkPlugin.CallLogsService.CreateCallLogRequest inValue = new CyberSharkPlugin.CallLogsService.CreateCallLogRequest();
            inValue.Body = new CyberSharkPlugin.CallLogsService.CreateCallLogRequestBody();
            inValue.Body.authUserName = authUserName;
            inValue.Body.authPassword = authPassword;
            inValue.Body.parameters = parameters;
            return ((CyberSharkPlugin.CallLogsService.svcCallLogsSoap)(this)).CreateCallLogAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CyberSharkPlugin.CallLogsService.CreateCallLog2Response CyberSharkPlugin.CallLogsService.svcCallLogsSoap.CreateCallLog2(CyberSharkPlugin.CallLogsService.CreateCallLog2Request request) {
            return base.Channel.CreateCallLog2(request);
        }
        
        public CyberSharkPlugin.CallLogsService.CallLogIdResult CreateCallLog2(string authUserName, string authPassword, CyberSharkPlugin.CallLogsService.ArrayOfString parameters) {
            CyberSharkPlugin.CallLogsService.CreateCallLog2Request inValue = new CyberSharkPlugin.CallLogsService.CreateCallLog2Request();
            inValue.Body = new CyberSharkPlugin.CallLogsService.CreateCallLog2RequestBody();
            inValue.Body.authUserName = authUserName;
            inValue.Body.authPassword = authPassword;
            inValue.Body.parameters = parameters;
            CyberSharkPlugin.CallLogsService.CreateCallLog2Response retVal = ((CyberSharkPlugin.CallLogsService.svcCallLogsSoap)(this)).CreateCallLog2(inValue);
            return retVal.Body.CreateCallLog2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CyberSharkPlugin.CallLogsService.CreateCallLog2Response> CyberSharkPlugin.CallLogsService.svcCallLogsSoap.CreateCallLog2Async(CyberSharkPlugin.CallLogsService.CreateCallLog2Request request) {
            return base.Channel.CreateCallLog2Async(request);
        }
        
        public System.Threading.Tasks.Task<CyberSharkPlugin.CallLogsService.CreateCallLog2Response> CreateCallLog2Async(string authUserName, string authPassword, CyberSharkPlugin.CallLogsService.ArrayOfString parameters) {
            CyberSharkPlugin.CallLogsService.CreateCallLog2Request inValue = new CyberSharkPlugin.CallLogsService.CreateCallLog2Request();
            inValue.Body = new CyberSharkPlugin.CallLogsService.CreateCallLog2RequestBody();
            inValue.Body.authUserName = authUserName;
            inValue.Body.authPassword = authPassword;
            inValue.Body.parameters = parameters;
            return ((CyberSharkPlugin.CallLogsService.svcCallLogsSoap)(this)).CreateCallLog2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CyberSharkPlugin.CallLogsService.ModifyCallLogResponse CyberSharkPlugin.CallLogsService.svcCallLogsSoap.ModifyCallLog(CyberSharkPlugin.CallLogsService.ModifyCallLogRequest request) {
            return base.Channel.ModifyCallLog(request);
        }
        
        public CyberSharkPlugin.CallLogsService.GenericResult ModifyCallLog(string authUserName, string authPassword, int logID, CyberSharkPlugin.CallLogsService.ArrayOfString parameters) {
            CyberSharkPlugin.CallLogsService.ModifyCallLogRequest inValue = new CyberSharkPlugin.CallLogsService.ModifyCallLogRequest();
            inValue.Body = new CyberSharkPlugin.CallLogsService.ModifyCallLogRequestBody();
            inValue.Body.authUserName = authUserName;
            inValue.Body.authPassword = authPassword;
            inValue.Body.logID = logID;
            inValue.Body.parameters = parameters;
            CyberSharkPlugin.CallLogsService.ModifyCallLogResponse retVal = ((CyberSharkPlugin.CallLogsService.svcCallLogsSoap)(this)).ModifyCallLog(inValue);
            return retVal.Body.ModifyCallLogResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CyberSharkPlugin.CallLogsService.ModifyCallLogResponse> CyberSharkPlugin.CallLogsService.svcCallLogsSoap.ModifyCallLogAsync(CyberSharkPlugin.CallLogsService.ModifyCallLogRequest request) {
            return base.Channel.ModifyCallLogAsync(request);
        }
        
        public System.Threading.Tasks.Task<CyberSharkPlugin.CallLogsService.ModifyCallLogResponse> ModifyCallLogAsync(string authUserName, string authPassword, int logID, CyberSharkPlugin.CallLogsService.ArrayOfString parameters) {
            CyberSharkPlugin.CallLogsService.ModifyCallLogRequest inValue = new CyberSharkPlugin.CallLogsService.ModifyCallLogRequest();
            inValue.Body = new CyberSharkPlugin.CallLogsService.ModifyCallLogRequestBody();
            inValue.Body.authUserName = authUserName;
            inValue.Body.authPassword = authPassword;
            inValue.Body.logID = logID;
            inValue.Body.parameters = parameters;
            return ((CyberSharkPlugin.CallLogsService.svcCallLogsSoap)(this)).ModifyCallLogAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CyberSharkPlugin.CallLogsService.DeleteCallLogResponse CyberSharkPlugin.CallLogsService.svcCallLogsSoap.DeleteCallLog(CyberSharkPlugin.CallLogsService.DeleteCallLogRequest request) {
            return base.Channel.DeleteCallLog(request);
        }
        
        public CyberSharkPlugin.CallLogsService.GenericResult DeleteCallLog(string authUserName, string authPassword, int logID) {
            CyberSharkPlugin.CallLogsService.DeleteCallLogRequest inValue = new CyberSharkPlugin.CallLogsService.DeleteCallLogRequest();
            inValue.Body = new CyberSharkPlugin.CallLogsService.DeleteCallLogRequestBody();
            inValue.Body.authUserName = authUserName;
            inValue.Body.authPassword = authPassword;
            inValue.Body.logID = logID;
            CyberSharkPlugin.CallLogsService.DeleteCallLogResponse retVal = ((CyberSharkPlugin.CallLogsService.svcCallLogsSoap)(this)).DeleteCallLog(inValue);
            return retVal.Body.DeleteCallLogResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CyberSharkPlugin.CallLogsService.DeleteCallLogResponse> CyberSharkPlugin.CallLogsService.svcCallLogsSoap.DeleteCallLogAsync(CyberSharkPlugin.CallLogsService.DeleteCallLogRequest request) {
            return base.Channel.DeleteCallLogAsync(request);
        }
        
        public System.Threading.Tasks.Task<CyberSharkPlugin.CallLogsService.DeleteCallLogResponse> DeleteCallLogAsync(string authUserName, string authPassword, int logID) {
            CyberSharkPlugin.CallLogsService.DeleteCallLogRequest inValue = new CyberSharkPlugin.CallLogsService.DeleteCallLogRequest();
            inValue.Body = new CyberSharkPlugin.CallLogsService.DeleteCallLogRequestBody();
            inValue.Body.authUserName = authUserName;
            inValue.Body.authPassword = authPassword;
            inValue.Body.logID = logID;
            return ((CyberSharkPlugin.CallLogsService.svcCallLogsSoap)(this)).DeleteCallLogAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CyberSharkPlugin.CallLogsService.GetCallLogResponse CyberSharkPlugin.CallLogsService.svcCallLogsSoap.GetCallLog(CyberSharkPlugin.CallLogsService.GetCallLogRequest request) {
            return base.Channel.GetCallLog(request);
        }
        
        public CyberSharkPlugin.CallLogsService.CallLogInfoResult GetCallLog(string authUserName, string authPassword, int logID) {
            CyberSharkPlugin.CallLogsService.GetCallLogRequest inValue = new CyberSharkPlugin.CallLogsService.GetCallLogRequest();
            inValue.Body = new CyberSharkPlugin.CallLogsService.GetCallLogRequestBody();
            inValue.Body.authUserName = authUserName;
            inValue.Body.authPassword = authPassword;
            inValue.Body.logID = logID;
            CyberSharkPlugin.CallLogsService.GetCallLogResponse retVal = ((CyberSharkPlugin.CallLogsService.svcCallLogsSoap)(this)).GetCallLog(inValue);
            return retVal.Body.GetCallLogResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CyberSharkPlugin.CallLogsService.GetCallLogResponse> CyberSharkPlugin.CallLogsService.svcCallLogsSoap.GetCallLogAsync(CyberSharkPlugin.CallLogsService.GetCallLogRequest request) {
            return base.Channel.GetCallLogAsync(request);
        }
        
        public System.Threading.Tasks.Task<CyberSharkPlugin.CallLogsService.GetCallLogResponse> GetCallLogAsync(string authUserName, string authPassword, int logID) {
            CyberSharkPlugin.CallLogsService.GetCallLogRequest inValue = new CyberSharkPlugin.CallLogsService.GetCallLogRequest();
            inValue.Body = new CyberSharkPlugin.CallLogsService.GetCallLogRequestBody();
            inValue.Body.authUserName = authUserName;
            inValue.Body.authPassword = authPassword;
            inValue.Body.logID = logID;
            return ((CyberSharkPlugin.CallLogsService.svcCallLogsSoap)(this)).GetCallLogAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CyberSharkPlugin.CallLogsService.GetCallLogByUserResponse CyberSharkPlugin.CallLogsService.svcCallLogsSoap.GetCallLogByUser(CyberSharkPlugin.CallLogsService.GetCallLogByUserRequest request) {
            return base.Channel.GetCallLogByUser(request);
        }
        
        public CyberSharkPlugin.CallLogsService.CallLogInfoResultArray GetCallLogByUser(string authUserName, string authPassword, int userID, System.DateTime dateCreatedStart, System.DateTime dateCreatedEnd) {
            CyberSharkPlugin.CallLogsService.GetCallLogByUserRequest inValue = new CyberSharkPlugin.CallLogsService.GetCallLogByUserRequest();
            inValue.Body = new CyberSharkPlugin.CallLogsService.GetCallLogByUserRequestBody();
            inValue.Body.authUserName = authUserName;
            inValue.Body.authPassword = authPassword;
            inValue.Body.userID = userID;
            inValue.Body.dateCreatedStart = dateCreatedStart;
            inValue.Body.dateCreatedEnd = dateCreatedEnd;
            CyberSharkPlugin.CallLogsService.GetCallLogByUserResponse retVal = ((CyberSharkPlugin.CallLogsService.svcCallLogsSoap)(this)).GetCallLogByUser(inValue);
            return retVal.Body.GetCallLogByUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CyberSharkPlugin.CallLogsService.GetCallLogByUserResponse> CyberSharkPlugin.CallLogsService.svcCallLogsSoap.GetCallLogByUserAsync(CyberSharkPlugin.CallLogsService.GetCallLogByUserRequest request) {
            return base.Channel.GetCallLogByUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<CyberSharkPlugin.CallLogsService.GetCallLogByUserResponse> GetCallLogByUserAsync(string authUserName, string authPassword, int userID, System.DateTime dateCreatedStart, System.DateTime dateCreatedEnd) {
            CyberSharkPlugin.CallLogsService.GetCallLogByUserRequest inValue = new CyberSharkPlugin.CallLogsService.GetCallLogByUserRequest();
            inValue.Body = new CyberSharkPlugin.CallLogsService.GetCallLogByUserRequestBody();
            inValue.Body.authUserName = authUserName;
            inValue.Body.authPassword = authPassword;
            inValue.Body.userID = userID;
            inValue.Body.dateCreatedStart = dateCreatedStart;
            inValue.Body.dateCreatedEnd = dateCreatedEnd;
            return ((CyberSharkPlugin.CallLogsService.svcCallLogsSoap)(this)).GetCallLogByUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CyberSharkPlugin.CallLogsService.GetCallLogByGroupResponse CyberSharkPlugin.CallLogsService.svcCallLogsSoap.GetCallLogByGroup(CyberSharkPlugin.CallLogsService.GetCallLogByGroupRequest request) {
            return base.Channel.GetCallLogByGroup(request);
        }
        
        public CyberSharkPlugin.CallLogsService.CallLogInfoResultArray GetCallLogByGroup(string authUserName, string authPassword, int groupID, System.DateTime dateCreatedStart, System.DateTime dateCreatedEnd) {
            CyberSharkPlugin.CallLogsService.GetCallLogByGroupRequest inValue = new CyberSharkPlugin.CallLogsService.GetCallLogByGroupRequest();
            inValue.Body = new CyberSharkPlugin.CallLogsService.GetCallLogByGroupRequestBody();
            inValue.Body.authUserName = authUserName;
            inValue.Body.authPassword = authPassword;
            inValue.Body.groupID = groupID;
            inValue.Body.dateCreatedStart = dateCreatedStart;
            inValue.Body.dateCreatedEnd = dateCreatedEnd;
            CyberSharkPlugin.CallLogsService.GetCallLogByGroupResponse retVal = ((CyberSharkPlugin.CallLogsService.svcCallLogsSoap)(this)).GetCallLogByGroup(inValue);
            return retVal.Body.GetCallLogByGroupResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CyberSharkPlugin.CallLogsService.GetCallLogByGroupResponse> CyberSharkPlugin.CallLogsService.svcCallLogsSoap.GetCallLogByGroupAsync(CyberSharkPlugin.CallLogsService.GetCallLogByGroupRequest request) {
            return base.Channel.GetCallLogByGroupAsync(request);
        }
        
        public System.Threading.Tasks.Task<CyberSharkPlugin.CallLogsService.GetCallLogByGroupResponse> GetCallLogByGroupAsync(string authUserName, string authPassword, int groupID, System.DateTime dateCreatedStart, System.DateTime dateCreatedEnd) {
            CyberSharkPlugin.CallLogsService.GetCallLogByGroupRequest inValue = new CyberSharkPlugin.CallLogsService.GetCallLogByGroupRequest();
            inValue.Body = new CyberSharkPlugin.CallLogsService.GetCallLogByGroupRequestBody();
            inValue.Body.authUserName = authUserName;
            inValue.Body.authPassword = authPassword;
            inValue.Body.groupID = groupID;
            inValue.Body.dateCreatedStart = dateCreatedStart;
            inValue.Body.dateCreatedEnd = dateCreatedEnd;
            return ((CyberSharkPlugin.CallLogsService.svcCallLogsSoap)(this)).GetCallLogByGroupAsync(inValue);
        }
    }
}
