//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSPluginForm.CallLogService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenericResult", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx")]
    [System.SerializableAttribute()]
    public partial class GenericResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool ResultField;
        
        private int ResultCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ResultCode {
            get {
                return this.ResultCodeField;
            }
            set {
                if ((this.ResultCodeField.Equals(value) != true)) {
                    this.ResultCodeField = value;
                    this.RaisePropertyChanged("ResultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallLogIdResult", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx")]
    [System.SerializableAttribute()]
    public partial class CallLogIdResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool ResultField;
        
        private int ResultCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        private int CallLogIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CallNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ResultCode {
            get {
                return this.ResultCodeField;
            }
            set {
                if ((this.ResultCodeField.Equals(value) != true)) {
                    this.ResultCodeField = value;
                    this.RaisePropertyChanged("ResultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int CallLogId {
            get {
                return this.CallLogIdField;
            }
            set {
                if ((this.CallLogIdField.Equals(value) != true)) {
                    this.CallLogIdField = value;
                    this.RaisePropertyChanged("CallLogId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CallNumber {
            get {
                return this.CallNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CallNumberField, value) != true)) {
                    this.CallNumberField = value;
                    this.RaisePropertyChanged("CallNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallLogInfoResult", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx")]
    [System.SerializableAttribute()]
    public partial class CallLogInfoResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool ResultField;
        
        private int ResultCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        private CSPluginForm.CallLogService.CallLogInfo CallLogField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ResultCode {
            get {
                return this.ResultCodeField;
            }
            set {
                if ((this.ResultCodeField.Equals(value) != true)) {
                    this.ResultCodeField = value;
                    this.RaisePropertyChanged("ResultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public CSPluginForm.CallLogService.CallLogInfo CallLog {
            get {
                return this.CallLogField;
            }
            set {
                if ((object.ReferenceEquals(this.CallLogField, value) != true)) {
                    this.CallLogField = value;
                    this.RaisePropertyChanged("CallLog");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallLogInfo", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx")]
    [System.SerializableAttribute()]
    public partial class CallLogInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        private System.DateTime StartTimeField;
        
        private System.DateTime EndTimeField;
        
        private System.DateTime DateCreatedField;
        
        private System.Nullable<System.DateTime> DateDeletedField;
        
        private int GroupIDField;
        
        private int AgentIDField;
        
        private int LogIDField;
        
        private bool IncomingCallField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CallNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((this.EndTimeField.Equals(value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime DateCreated {
            get {
                return this.DateCreatedField;
            }
            set {
                if ((this.DateCreatedField.Equals(value) != true)) {
                    this.DateCreatedField = value;
                    this.RaisePropertyChanged("DateCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.Nullable<System.DateTime> DateDeleted {
            get {
                return this.DateDeletedField;
            }
            set {
                if ((this.DateDeletedField.Equals(value) != true)) {
                    this.DateDeletedField = value;
                    this.RaisePropertyChanged("DateDeleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int GroupID {
            get {
                return this.GroupIDField;
            }
            set {
                if ((this.GroupIDField.Equals(value) != true)) {
                    this.GroupIDField = value;
                    this.RaisePropertyChanged("GroupID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int AgentID {
            get {
                return this.AgentIDField;
            }
            set {
                if ((this.AgentIDField.Equals(value) != true)) {
                    this.AgentIDField = value;
                    this.RaisePropertyChanged("AgentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public int LogID {
            get {
                return this.LogIDField;
            }
            set {
                if ((this.LogIDField.Equals(value) != true)) {
                    this.LogIDField = value;
                    this.RaisePropertyChanged("LogID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public bool IncomingCall {
            get {
                return this.IncomingCallField;
            }
            set {
                if ((this.IncomingCallField.Equals(value) != true)) {
                    this.IncomingCallField = value;
                    this.RaisePropertyChanged("IncomingCall");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string CallNumber {
            get {
                return this.CallNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CallNumberField, value) != true)) {
                    this.CallNumberField = value;
                    this.RaisePropertyChanged("CallNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallLogInfoResultArray", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx")]
    [System.SerializableAttribute()]
    public partial class CallLogInfoResultArray : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool ResultField;
        
        private int ResultCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CSPluginForm.CallLogService.CallLogInfo[] CallLogsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ResultCode {
            get {
                return this.ResultCodeField;
            }
            set {
                if ((this.ResultCodeField.Equals(value) != true)) {
                    this.ResultCodeField = value;
                    this.RaisePropertyChanged("ResultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public CSPluginForm.CallLogService.CallLogInfo[] CallLogs {
            get {
                return this.CallLogsField;
            }
            set {
                if ((object.ReferenceEquals(this.CallLogsField, value) != true)) {
                    this.CallLogsField = value;
                    this.RaisePropertyChanged("CallLogs");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx", ConfigurationName="CallLogService.svcCallLogsSoap")]
    public interface svcCallLogsSoap {
        
        // CODEGEN: Generating message contract since element name authUserName from namespace http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx/CreateCallLog" +
            "", ReplyAction="*")]
        CSPluginForm.CallLogService.CreateCallLogResponse CreateCallLog(CSPluginForm.CallLogService.CreateCallLogRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx/CreateCallLog" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task<CSPluginForm.CallLogService.CreateCallLogResponse> CreateCallLogAsync(CSPluginForm.CallLogService.CreateCallLogRequest request);
        
        // CODEGEN: Generating message contract since element name authUserName from namespace http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx/CreateCallLog" +
            "2", ReplyAction="*")]
        CSPluginForm.CallLogService.CreateCallLog2Response CreateCallLog2(CSPluginForm.CallLogService.CreateCallLog2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx/CreateCallLog" +
            "2", ReplyAction="*")]
        System.Threading.Tasks.Task<CSPluginForm.CallLogService.CreateCallLog2Response> CreateCallLog2Async(CSPluginForm.CallLogService.CreateCallLog2Request request);
        
        // CODEGEN: Generating message contract since element name authUserName from namespace http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx/ModifyCallLog" +
            "", ReplyAction="*")]
        CSPluginForm.CallLogService.ModifyCallLogResponse ModifyCallLog(CSPluginForm.CallLogService.ModifyCallLogRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx/ModifyCallLog" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task<CSPluginForm.CallLogService.ModifyCallLogResponse> ModifyCallLogAsync(CSPluginForm.CallLogService.ModifyCallLogRequest request);
        
        // CODEGEN: Generating message contract since element name authUserName from namespace http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx/DeleteCallLog" +
            "", ReplyAction="*")]
        CSPluginForm.CallLogService.DeleteCallLogResponse DeleteCallLog(CSPluginForm.CallLogService.DeleteCallLogRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx/DeleteCallLog" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task<CSPluginForm.CallLogService.DeleteCallLogResponse> DeleteCallLogAsync(CSPluginForm.CallLogService.DeleteCallLogRequest request);
        
        // CODEGEN: Generating message contract since element name authUserName from namespace http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx/GetCallLog", ReplyAction="*")]
        CSPluginForm.CallLogService.GetCallLogResponse GetCallLog(CSPluginForm.CallLogService.GetCallLogRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx/GetCallLog", ReplyAction="*")]
        System.Threading.Tasks.Task<CSPluginForm.CallLogService.GetCallLogResponse> GetCallLogAsync(CSPluginForm.CallLogService.GetCallLogRequest request);
        
        // CODEGEN: Generating message contract since element name authUserName from namespace http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx/GetCallLogByU" +
            "ser", ReplyAction="*")]
        CSPluginForm.CallLogService.GetCallLogByUserResponse GetCallLogByUser(CSPluginForm.CallLogService.GetCallLogByUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx/GetCallLogByU" +
            "ser", ReplyAction="*")]
        System.Threading.Tasks.Task<CSPluginForm.CallLogService.GetCallLogByUserResponse> GetCallLogByUserAsync(CSPluginForm.CallLogService.GetCallLogByUserRequest request);
        
        // CODEGEN: Generating message contract since element name authUserName from namespace http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx/GetCallLogByG" +
            "roup", ReplyAction="*")]
        CSPluginForm.CallLogService.GetCallLogByGroupResponse GetCallLogByGroup(CSPluginForm.CallLogService.GetCallLogByGroupRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx/GetCallLogByG" +
            "roup", ReplyAction="*")]
        System.Threading.Tasks.Task<CSPluginForm.CallLogService.GetCallLogByGroupResponse> GetCallLogByGroupAsync(CSPluginForm.CallLogService.GetCallLogByGroupRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateCallLogRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateCallLog", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx", Order=0)]
        public CSPluginForm.CallLogService.CreateCallLogRequestBody Body;
        
        public CreateCallLogRequest() {
        }
        
        public CreateCallLogRequest(CSPluginForm.CallLogService.CreateCallLogRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx")]
    public partial class CreateCallLogRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string authUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string authPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public CSPluginForm.CallLogService.ArrayOfString parameters;
        
        public CreateCallLogRequestBody() {
        }
        
        public CreateCallLogRequestBody(string authUserName, string authPassword, CSPluginForm.CallLogService.ArrayOfString parameters) {
            this.authUserName = authUserName;
            this.authPassword = authPassword;
            this.parameters = parameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateCallLogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateCallLogResponse", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx", Order=0)]
        public CSPluginForm.CallLogService.CreateCallLogResponseBody Body;
        
        public CreateCallLogResponse() {
        }
        
        public CreateCallLogResponse(CSPluginForm.CallLogService.CreateCallLogResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx")]
    public partial class CreateCallLogResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CSPluginForm.CallLogService.GenericResult CreateCallLogResult;
        
        public CreateCallLogResponseBody() {
        }
        
        public CreateCallLogResponseBody(CSPluginForm.CallLogService.GenericResult CreateCallLogResult) {
            this.CreateCallLogResult = CreateCallLogResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateCallLog2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateCallLog2", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx", Order=0)]
        public CSPluginForm.CallLogService.CreateCallLog2RequestBody Body;
        
        public CreateCallLog2Request() {
        }
        
        public CreateCallLog2Request(CSPluginForm.CallLogService.CreateCallLog2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx")]
    public partial class CreateCallLog2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string authUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string authPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public CSPluginForm.CallLogService.ArrayOfString parameters;
        
        public CreateCallLog2RequestBody() {
        }
        
        public CreateCallLog2RequestBody(string authUserName, string authPassword, CSPluginForm.CallLogService.ArrayOfString parameters) {
            this.authUserName = authUserName;
            this.authPassword = authPassword;
            this.parameters = parameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateCallLog2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateCallLog2Response", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx", Order=0)]
        public CSPluginForm.CallLogService.CreateCallLog2ResponseBody Body;
        
        public CreateCallLog2Response() {
        }
        
        public CreateCallLog2Response(CSPluginForm.CallLogService.CreateCallLog2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx")]
    public partial class CreateCallLog2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CSPluginForm.CallLogService.CallLogIdResult CreateCallLog2Result;
        
        public CreateCallLog2ResponseBody() {
        }
        
        public CreateCallLog2ResponseBody(CSPluginForm.CallLogService.CallLogIdResult CreateCallLog2Result) {
            this.CreateCallLog2Result = CreateCallLog2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModifyCallLogRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModifyCallLog", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx", Order=0)]
        public CSPluginForm.CallLogService.ModifyCallLogRequestBody Body;
        
        public ModifyCallLogRequest() {
        }
        
        public ModifyCallLogRequest(CSPluginForm.CallLogService.ModifyCallLogRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx")]
    public partial class ModifyCallLogRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string authUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string authPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int logID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public CSPluginForm.CallLogService.ArrayOfString parameters;
        
        public ModifyCallLogRequestBody() {
        }
        
        public ModifyCallLogRequestBody(string authUserName, string authPassword, int logID, CSPluginForm.CallLogService.ArrayOfString parameters) {
            this.authUserName = authUserName;
            this.authPassword = authPassword;
            this.logID = logID;
            this.parameters = parameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModifyCallLogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModifyCallLogResponse", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx", Order=0)]
        public CSPluginForm.CallLogService.ModifyCallLogResponseBody Body;
        
        public ModifyCallLogResponse() {
        }
        
        public ModifyCallLogResponse(CSPluginForm.CallLogService.ModifyCallLogResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx")]
    public partial class ModifyCallLogResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CSPluginForm.CallLogService.GenericResult ModifyCallLogResult;
        
        public ModifyCallLogResponseBody() {
        }
        
        public ModifyCallLogResponseBody(CSPluginForm.CallLogService.GenericResult ModifyCallLogResult) {
            this.ModifyCallLogResult = ModifyCallLogResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteCallLogRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteCallLog", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx", Order=0)]
        public CSPluginForm.CallLogService.DeleteCallLogRequestBody Body;
        
        public DeleteCallLogRequest() {
        }
        
        public DeleteCallLogRequest(CSPluginForm.CallLogService.DeleteCallLogRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx")]
    public partial class DeleteCallLogRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string authUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string authPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int logID;
        
        public DeleteCallLogRequestBody() {
        }
        
        public DeleteCallLogRequestBody(string authUserName, string authPassword, int logID) {
            this.authUserName = authUserName;
            this.authPassword = authPassword;
            this.logID = logID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteCallLogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteCallLogResponse", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx", Order=0)]
        public CSPluginForm.CallLogService.DeleteCallLogResponseBody Body;
        
        public DeleteCallLogResponse() {
        }
        
        public DeleteCallLogResponse(CSPluginForm.CallLogService.DeleteCallLogResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx")]
    public partial class DeleteCallLogResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CSPluginForm.CallLogService.GenericResult DeleteCallLogResult;
        
        public DeleteCallLogResponseBody() {
        }
        
        public DeleteCallLogResponseBody(CSPluginForm.CallLogService.GenericResult DeleteCallLogResult) {
            this.DeleteCallLogResult = DeleteCallLogResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCallLogRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCallLog", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx", Order=0)]
        public CSPluginForm.CallLogService.GetCallLogRequestBody Body;
        
        public GetCallLogRequest() {
        }
        
        public GetCallLogRequest(CSPluginForm.CallLogService.GetCallLogRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx")]
    public partial class GetCallLogRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string authUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string authPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int logID;
        
        public GetCallLogRequestBody() {
        }
        
        public GetCallLogRequestBody(string authUserName, string authPassword, int logID) {
            this.authUserName = authUserName;
            this.authPassword = authPassword;
            this.logID = logID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCallLogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCallLogResponse", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx", Order=0)]
        public CSPluginForm.CallLogService.GetCallLogResponseBody Body;
        
        public GetCallLogResponse() {
        }
        
        public GetCallLogResponse(CSPluginForm.CallLogService.GetCallLogResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx")]
    public partial class GetCallLogResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CSPluginForm.CallLogService.CallLogInfoResult GetCallLogResult;
        
        public GetCallLogResponseBody() {
        }
        
        public GetCallLogResponseBody(CSPluginForm.CallLogService.CallLogInfoResult GetCallLogResult) {
            this.GetCallLogResult = GetCallLogResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCallLogByUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCallLogByUser", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx", Order=0)]
        public CSPluginForm.CallLogService.GetCallLogByUserRequestBody Body;
        
        public GetCallLogByUserRequest() {
        }
        
        public GetCallLogByUserRequest(CSPluginForm.CallLogService.GetCallLogByUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx")]
    public partial class GetCallLogByUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string authUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string authPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int userID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime dateCreatedStart;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime dateCreatedEnd;
        
        public GetCallLogByUserRequestBody() {
        }
        
        public GetCallLogByUserRequestBody(string authUserName, string authPassword, int userID, System.DateTime dateCreatedStart, System.DateTime dateCreatedEnd) {
            this.authUserName = authUserName;
            this.authPassword = authPassword;
            this.userID = userID;
            this.dateCreatedStart = dateCreatedStart;
            this.dateCreatedEnd = dateCreatedEnd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCallLogByUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCallLogByUserResponse", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx", Order=0)]
        public CSPluginForm.CallLogService.GetCallLogByUserResponseBody Body;
        
        public GetCallLogByUserResponse() {
        }
        
        public GetCallLogByUserResponse(CSPluginForm.CallLogService.GetCallLogByUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx")]
    public partial class GetCallLogByUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CSPluginForm.CallLogService.CallLogInfoResultArray GetCallLogByUserResult;
        
        public GetCallLogByUserResponseBody() {
        }
        
        public GetCallLogByUserResponseBody(CSPluginForm.CallLogService.CallLogInfoResultArray GetCallLogByUserResult) {
            this.GetCallLogByUserResult = GetCallLogByUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCallLogByGroupRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCallLogByGroup", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx", Order=0)]
        public CSPluginForm.CallLogService.GetCallLogByGroupRequestBody Body;
        
        public GetCallLogByGroupRequest() {
        }
        
        public GetCallLogByGroupRequest(CSPluginForm.CallLogService.GetCallLogByGroupRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx")]
    public partial class GetCallLogByGroupRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string authUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string authPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int groupID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime dateCreatedStart;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime dateCreatedEnd;
        
        public GetCallLogByGroupRequestBody() {
        }
        
        public GetCallLogByGroupRequestBody(string authUserName, string authPassword, int groupID, System.DateTime dateCreatedStart, System.DateTime dateCreatedEnd) {
            this.authUserName = authUserName;
            this.authPassword = authPassword;
            this.groupID = groupID;
            this.dateCreatedStart = dateCreatedStart;
            this.dateCreatedEnd = dateCreatedEnd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCallLogByGroupResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCallLogByGroupResponse", Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx", Order=0)]
        public CSPluginForm.CallLogService.GetCallLogByGroupResponseBody Body;
        
        public GetCallLogByGroupResponse() {
        }
        
        public GetCallLogByGroupResponse(CSPluginForm.CallLogService.GetCallLogByGroupResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.smartertools.com/SmarterTrack/Services2/svcCallLogs.asmx")]
    public partial class GetCallLogByGroupResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CSPluginForm.CallLogService.CallLogInfoResultArray GetCallLogByGroupResult;
        
        public GetCallLogByGroupResponseBody() {
        }
        
        public GetCallLogByGroupResponseBody(CSPluginForm.CallLogService.CallLogInfoResultArray GetCallLogByGroupResult) {
            this.GetCallLogByGroupResult = GetCallLogByGroupResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface svcCallLogsSoapChannel : CSPluginForm.CallLogService.svcCallLogsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class svcCallLogsSoapClient : System.ServiceModel.ClientBase<CSPluginForm.CallLogService.svcCallLogsSoap>, CSPluginForm.CallLogService.svcCallLogsSoap {
        
        public svcCallLogsSoapClient() {
        }
        
        public svcCallLogsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public svcCallLogsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public svcCallLogsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public svcCallLogsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CSPluginForm.CallLogService.CreateCallLogResponse CSPluginForm.CallLogService.svcCallLogsSoap.CreateCallLog(CSPluginForm.CallLogService.CreateCallLogRequest request) {
            return base.Channel.CreateCallLog(request);
        }
        
        public CSPluginForm.CallLogService.GenericResult CreateCallLog(string authUserName, string authPassword, CSPluginForm.CallLogService.ArrayOfString parameters) {
            CSPluginForm.CallLogService.CreateCallLogRequest inValue = new CSPluginForm.CallLogService.CreateCallLogRequest();
            inValue.Body = new CSPluginForm.CallLogService.CreateCallLogRequestBody();
            inValue.Body.authUserName = authUserName;
            inValue.Body.authPassword = authPassword;
            inValue.Body.parameters = parameters;
            CSPluginForm.CallLogService.CreateCallLogResponse retVal = ((CSPluginForm.CallLogService.svcCallLogsSoap)(this)).CreateCallLog(inValue);
            return retVal.Body.CreateCallLogResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CSPluginForm.CallLogService.CreateCallLogResponse> CSPluginForm.CallLogService.svcCallLogsSoap.CreateCallLogAsync(CSPluginForm.CallLogService.CreateCallLogRequest request) {
            return base.Channel.CreateCallLogAsync(request);
        }
        
        public System.Threading.Tasks.Task<CSPluginForm.CallLogService.CreateCallLogResponse> CreateCallLogAsync(string authUserName, string authPassword, CSPluginForm.CallLogService.ArrayOfString parameters) {
            CSPluginForm.CallLogService.CreateCallLogRequest inValue = new CSPluginForm.CallLogService.CreateCallLogRequest();
            inValue.Body = new CSPluginForm.CallLogService.CreateCallLogRequestBody();
            inValue.Body.authUserName = authUserName;
            inValue.Body.authPassword = authPassword;
            inValue.Body.parameters = parameters;
            return ((CSPluginForm.CallLogService.svcCallLogsSoap)(this)).CreateCallLogAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CSPluginForm.CallLogService.CreateCallLog2Response CSPluginForm.CallLogService.svcCallLogsSoap.CreateCallLog2(CSPluginForm.CallLogService.CreateCallLog2Request request) {
            return base.Channel.CreateCallLog2(request);
        }
        
        public CSPluginForm.CallLogService.CallLogIdResult CreateCallLog2(string authUserName, string authPassword, CSPluginForm.CallLogService.ArrayOfString parameters) {
            CSPluginForm.CallLogService.CreateCallLog2Request inValue = new CSPluginForm.CallLogService.CreateCallLog2Request();
            inValue.Body = new CSPluginForm.CallLogService.CreateCallLog2RequestBody();
            inValue.Body.authUserName = authUserName;
            inValue.Body.authPassword = authPassword;
            inValue.Body.parameters = parameters;
            CSPluginForm.CallLogService.CreateCallLog2Response retVal = ((CSPluginForm.CallLogService.svcCallLogsSoap)(this)).CreateCallLog2(inValue);
            return retVal.Body.CreateCallLog2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CSPluginForm.CallLogService.CreateCallLog2Response> CSPluginForm.CallLogService.svcCallLogsSoap.CreateCallLog2Async(CSPluginForm.CallLogService.CreateCallLog2Request request) {
            return base.Channel.CreateCallLog2Async(request);
        }
        
        public System.Threading.Tasks.Task<CSPluginForm.CallLogService.CreateCallLog2Response> CreateCallLog2Async(string authUserName, string authPassword, CSPluginForm.CallLogService.ArrayOfString parameters) {
            CSPluginForm.CallLogService.CreateCallLog2Request inValue = new CSPluginForm.CallLogService.CreateCallLog2Request();
            inValue.Body = new CSPluginForm.CallLogService.CreateCallLog2RequestBody();
            inValue.Body.authUserName = authUserName;
            inValue.Body.authPassword = authPassword;
            inValue.Body.parameters = parameters;
            return ((CSPluginForm.CallLogService.svcCallLogsSoap)(this)).CreateCallLog2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CSPluginForm.CallLogService.ModifyCallLogResponse CSPluginForm.CallLogService.svcCallLogsSoap.ModifyCallLog(CSPluginForm.CallLogService.ModifyCallLogRequest request) {
            return base.Channel.ModifyCallLog(request);
        }
        
        public CSPluginForm.CallLogService.GenericResult ModifyCallLog(string authUserName, string authPassword, int logID, CSPluginForm.CallLogService.ArrayOfString parameters) {
            CSPluginForm.CallLogService.ModifyCallLogRequest inValue = new CSPluginForm.CallLogService.ModifyCallLogRequest();
            inValue.Body = new CSPluginForm.CallLogService.ModifyCallLogRequestBody();
            inValue.Body.authUserName = authUserName;
            inValue.Body.authPassword = authPassword;
            inValue.Body.logID = logID;
            inValue.Body.parameters = parameters;
            CSPluginForm.CallLogService.ModifyCallLogResponse retVal = ((CSPluginForm.CallLogService.svcCallLogsSoap)(this)).ModifyCallLog(inValue);
            return retVal.Body.ModifyCallLogResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CSPluginForm.CallLogService.ModifyCallLogResponse> CSPluginForm.CallLogService.svcCallLogsSoap.ModifyCallLogAsync(CSPluginForm.CallLogService.ModifyCallLogRequest request) {
            return base.Channel.ModifyCallLogAsync(request);
        }
        
        public System.Threading.Tasks.Task<CSPluginForm.CallLogService.ModifyCallLogResponse> ModifyCallLogAsync(string authUserName, string authPassword, int logID, CSPluginForm.CallLogService.ArrayOfString parameters) {
            CSPluginForm.CallLogService.ModifyCallLogRequest inValue = new CSPluginForm.CallLogService.ModifyCallLogRequest();
            inValue.Body = new CSPluginForm.CallLogService.ModifyCallLogRequestBody();
            inValue.Body.authUserName = authUserName;
            inValue.Body.authPassword = authPassword;
            inValue.Body.logID = logID;
            inValue.Body.parameters = parameters;
            return ((CSPluginForm.CallLogService.svcCallLogsSoap)(this)).ModifyCallLogAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CSPluginForm.CallLogService.DeleteCallLogResponse CSPluginForm.CallLogService.svcCallLogsSoap.DeleteCallLog(CSPluginForm.CallLogService.DeleteCallLogRequest request) {
            return base.Channel.DeleteCallLog(request);
        }
        
        public CSPluginForm.CallLogService.GenericResult DeleteCallLog(string authUserName, string authPassword, int logID) {
            CSPluginForm.CallLogService.DeleteCallLogRequest inValue = new CSPluginForm.CallLogService.DeleteCallLogRequest();
            inValue.Body = new CSPluginForm.CallLogService.DeleteCallLogRequestBody();
            inValue.Body.authUserName = authUserName;
            inValue.Body.authPassword = authPassword;
            inValue.Body.logID = logID;
            CSPluginForm.CallLogService.DeleteCallLogResponse retVal = ((CSPluginForm.CallLogService.svcCallLogsSoap)(this)).DeleteCallLog(inValue);
            return retVal.Body.DeleteCallLogResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CSPluginForm.CallLogService.DeleteCallLogResponse> CSPluginForm.CallLogService.svcCallLogsSoap.DeleteCallLogAsync(CSPluginForm.CallLogService.DeleteCallLogRequest request) {
            return base.Channel.DeleteCallLogAsync(request);
        }
        
        public System.Threading.Tasks.Task<CSPluginForm.CallLogService.DeleteCallLogResponse> DeleteCallLogAsync(string authUserName, string authPassword, int logID) {
            CSPluginForm.CallLogService.DeleteCallLogRequest inValue = new CSPluginForm.CallLogService.DeleteCallLogRequest();
            inValue.Body = new CSPluginForm.CallLogService.DeleteCallLogRequestBody();
            inValue.Body.authUserName = authUserName;
            inValue.Body.authPassword = authPassword;
            inValue.Body.logID = logID;
            return ((CSPluginForm.CallLogService.svcCallLogsSoap)(this)).DeleteCallLogAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CSPluginForm.CallLogService.GetCallLogResponse CSPluginForm.CallLogService.svcCallLogsSoap.GetCallLog(CSPluginForm.CallLogService.GetCallLogRequest request) {
            return base.Channel.GetCallLog(request);
        }
        
        public CSPluginForm.CallLogService.CallLogInfoResult GetCallLog(string authUserName, string authPassword, int logID) {
            CSPluginForm.CallLogService.GetCallLogRequest inValue = new CSPluginForm.CallLogService.GetCallLogRequest();
            inValue.Body = new CSPluginForm.CallLogService.GetCallLogRequestBody();
            inValue.Body.authUserName = authUserName;
            inValue.Body.authPassword = authPassword;
            inValue.Body.logID = logID;
            CSPluginForm.CallLogService.GetCallLogResponse retVal = ((CSPluginForm.CallLogService.svcCallLogsSoap)(this)).GetCallLog(inValue);
            return retVal.Body.GetCallLogResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CSPluginForm.CallLogService.GetCallLogResponse> CSPluginForm.CallLogService.svcCallLogsSoap.GetCallLogAsync(CSPluginForm.CallLogService.GetCallLogRequest request) {
            return base.Channel.GetCallLogAsync(request);
        }
        
        public System.Threading.Tasks.Task<CSPluginForm.CallLogService.GetCallLogResponse> GetCallLogAsync(string authUserName, string authPassword, int logID) {
            CSPluginForm.CallLogService.GetCallLogRequest inValue = new CSPluginForm.CallLogService.GetCallLogRequest();
            inValue.Body = new CSPluginForm.CallLogService.GetCallLogRequestBody();
            inValue.Body.authUserName = authUserName;
            inValue.Body.authPassword = authPassword;
            inValue.Body.logID = logID;
            return ((CSPluginForm.CallLogService.svcCallLogsSoap)(this)).GetCallLogAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CSPluginForm.CallLogService.GetCallLogByUserResponse CSPluginForm.CallLogService.svcCallLogsSoap.GetCallLogByUser(CSPluginForm.CallLogService.GetCallLogByUserRequest request) {
            return base.Channel.GetCallLogByUser(request);
        }
        
        public CSPluginForm.CallLogService.CallLogInfoResultArray GetCallLogByUser(string authUserName, string authPassword, int userID, System.DateTime dateCreatedStart, System.DateTime dateCreatedEnd) {
            CSPluginForm.CallLogService.GetCallLogByUserRequest inValue = new CSPluginForm.CallLogService.GetCallLogByUserRequest();
            inValue.Body = new CSPluginForm.CallLogService.GetCallLogByUserRequestBody();
            inValue.Body.authUserName = authUserName;
            inValue.Body.authPassword = authPassword;
            inValue.Body.userID = userID;
            inValue.Body.dateCreatedStart = dateCreatedStart;
            inValue.Body.dateCreatedEnd = dateCreatedEnd;
            CSPluginForm.CallLogService.GetCallLogByUserResponse retVal = ((CSPluginForm.CallLogService.svcCallLogsSoap)(this)).GetCallLogByUser(inValue);
            return retVal.Body.GetCallLogByUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CSPluginForm.CallLogService.GetCallLogByUserResponse> CSPluginForm.CallLogService.svcCallLogsSoap.GetCallLogByUserAsync(CSPluginForm.CallLogService.GetCallLogByUserRequest request) {
            return base.Channel.GetCallLogByUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<CSPluginForm.CallLogService.GetCallLogByUserResponse> GetCallLogByUserAsync(string authUserName, string authPassword, int userID, System.DateTime dateCreatedStart, System.DateTime dateCreatedEnd) {
            CSPluginForm.CallLogService.GetCallLogByUserRequest inValue = new CSPluginForm.CallLogService.GetCallLogByUserRequest();
            inValue.Body = new CSPluginForm.CallLogService.GetCallLogByUserRequestBody();
            inValue.Body.authUserName = authUserName;
            inValue.Body.authPassword = authPassword;
            inValue.Body.userID = userID;
            inValue.Body.dateCreatedStart = dateCreatedStart;
            inValue.Body.dateCreatedEnd = dateCreatedEnd;
            return ((CSPluginForm.CallLogService.svcCallLogsSoap)(this)).GetCallLogByUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CSPluginForm.CallLogService.GetCallLogByGroupResponse CSPluginForm.CallLogService.svcCallLogsSoap.GetCallLogByGroup(CSPluginForm.CallLogService.GetCallLogByGroupRequest request) {
            return base.Channel.GetCallLogByGroup(request);
        }
        
        public CSPluginForm.CallLogService.CallLogInfoResultArray GetCallLogByGroup(string authUserName, string authPassword, int groupID, System.DateTime dateCreatedStart, System.DateTime dateCreatedEnd) {
            CSPluginForm.CallLogService.GetCallLogByGroupRequest inValue = new CSPluginForm.CallLogService.GetCallLogByGroupRequest();
            inValue.Body = new CSPluginForm.CallLogService.GetCallLogByGroupRequestBody();
            inValue.Body.authUserName = authUserName;
            inValue.Body.authPassword = authPassword;
            inValue.Body.groupID = groupID;
            inValue.Body.dateCreatedStart = dateCreatedStart;
            inValue.Body.dateCreatedEnd = dateCreatedEnd;
            CSPluginForm.CallLogService.GetCallLogByGroupResponse retVal = ((CSPluginForm.CallLogService.svcCallLogsSoap)(this)).GetCallLogByGroup(inValue);
            return retVal.Body.GetCallLogByGroupResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CSPluginForm.CallLogService.GetCallLogByGroupResponse> CSPluginForm.CallLogService.svcCallLogsSoap.GetCallLogByGroupAsync(CSPluginForm.CallLogService.GetCallLogByGroupRequest request) {
            return base.Channel.GetCallLogByGroupAsync(request);
        }
        
        public System.Threading.Tasks.Task<CSPluginForm.CallLogService.GetCallLogByGroupResponse> GetCallLogByGroupAsync(string authUserName, string authPassword, int groupID, System.DateTime dateCreatedStart, System.DateTime dateCreatedEnd) {
            CSPluginForm.CallLogService.GetCallLogByGroupRequest inValue = new CSPluginForm.CallLogService.GetCallLogByGroupRequest();
            inValue.Body = new CSPluginForm.CallLogService.GetCallLogByGroupRequestBody();
            inValue.Body.authUserName = authUserName;
            inValue.Body.authPassword = authPassword;
            inValue.Body.groupID = groupID;
            inValue.Body.dateCreatedStart = dateCreatedStart;
            inValue.Body.dateCreatedEnd = dateCreatedEnd;
            return ((CSPluginForm.CallLogService.svcCallLogsSoap)(this)).GetCallLogByGroupAsync(inValue);
        }
    }
}
